version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: meetingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_NAME: meetingdb
      DB_PASS: postgres
      DB_PORT: 5432
    ports:
      - "3000:3000"

volumes:
  postgres_data:
